# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=200)),
                ('Company_Location', models.CharField(max_length=200)),
                ('Last_Contact_Date', models.DateTimeField(verbose_name='last contact')),
                ('Contact_Name', models.CharField(max_length=200)),
                ('Contact_Email', models.EmailField(max_length=200)),
                ('Contact_PhoneNumber', models.CharField(max_length=12)),
                ('Job_Keywords', models.CharField(max_length=200)),
            ],
        ),
    ]
